on: 
  schedule:
    - cron: '30 * * * *'

jobs:
  using-schedule-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Show a message
        run: echo 'Bem-vindo!'
      - name: Multiple commands
        run: |
          node -v
          npm -v